import type { Metadata } from "next";

import "./globals.css";
import {
  poppinsFont,
  rokkittFont,
  playpen,
  mali,
  ubuntu,
  rubik,
  raj,
  mPlus,
  orbit,
  philosopher,
  fahkwang,
  upright,
  lora,
  marri,
} from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={` ${rokkittFont.variable}  ${poppinsFont.variable} ${playpen.variable} ${playpen.variable} ${mali.variable} ${ubuntu.variable} ${rubik.variable}
      ${raj.variable} ${mPlus.variable} ${orbit.variable} ${philosopher.variable} ${fahkwang.variable} ${upright.variable}
       ${lora.variable} ${marri.variable} font-poppins`}
      >
        {children}
      </body>
    </html>
  );
}
