import type { Metadata } from "next";
import {
  Swanky_and_Moo_Moo,
  Shadows_Into_Light_Two,
  Architects_Daughter,
  PT_Sans_Narrow,
  Ubuntu,
  PT_Sans,
  Bodoni_Moda,
  Rokkitt,
  Gluten,
  Expletus_Sans,
  Edu_QLD_Beginner,
  Poppins,
} from "next/font/google";
import "./globals.css";

// const inter = Swanky_and_Moo_Moo({ subsets: ["latin"], weight: ["400"] });
// const inter = Shadows_Into_Light_Two({ subsets: ["latin"], weight: ["400"] });
const inter = Architects_Daughter({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
